### ISSUE TITLE
Head/hand tracking doesn't work properly for some avatars

### ISSUE THREAD

**Issue by Lyneira** [nicoco007/BeatSaberCustomAvatars#65] opened 2020-09-08 06:49 UTC
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5186505/_latest.log)
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.**

**Desktop (please complete the following information):**
- Operating system: Windows 10
- Headset and controllers: Valve Index

**Describe the bug**
Head and hand tracking for some avatars isn't working properly. The head and hands follow the headset and controllers a little but the body doesn't move along with it, and the feet are stuck in place in the middle of the room.

The Lightning avatar can be found here: https://modelsaber.com/Avatars/?id=1572745808&pc
The same problem also occurs with these RWBY avatars from the same creator:
* Ruby: https://modelsaber.com/Avatars/?id=1572745588&pc
* Weiss: https://modelsaber.com/Avatars/?id=1572745616&pc
* Blake: https://modelsaber.com/Avatars/?id=1572745555&pc
* Yang: https://modelsaber.com/Avatars/?id=1572745649&pc

I should add that the Lightning avatar was working properly until 5.0.0 beta 7, perhaps beta 8 as well though I didn't get a chance to test it after Beat Saber updated to 1.11.

**Steps to reproduce**
1. Download and install the Lightning avatar from the link above.
2. Select Lightning as avatar in the Custom Avatars menu.
3. The tracking problem should be immediately apparent.

**Expected behavior**
The avatar's body should move in the same way other avatars do.

**Screenshots**

![lightning-tracking-problem](https://user-images.githubusercontent.com/1153438/92441783-1b6e3680-f1af-11ea-9340-539125000fb3.jpg)

**Comment by nicoco007** [comment] 2020-09-16 20:26
Looks like this is caused by a fix I made for an other issue. I'll see what I can do. If I can't get both to work, a fix for this problem will most likely take precedence because the other fix is breaking what used to be expected/standard behavior.

**Comment by nicoco007** [comment] 2020-09-17 03:41
I've fixed this in 0d7744d which will be included in the next release. For now, you can try out [this version](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5236148/BeatSaberCustomAvatars-0d7744d-RELEASE.zip) if you'd like, though other stuff might be broken.

**Closed by nicoco007** 2020-09-17 03:41 UTC
Labels: bug

**Comment by Lyneira** [comment] 2020-09-18 10:38
I've tried out the version you linked and the Lightning avatar as well as the others are now fixed, thank you!
