### ISSUE TITLE
Feet in weird positions after player movement in Noodle map

### ISSUE THREAD

**Issue by Stellar-Lily** [nicoco007/BeatSaberCustomAvatars#127] opened 2022-01-12 15:17 UTC
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.**
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/7855559/_latest.log)

**Desktop (please complete the following information):**
- Operating system: Windows 11 Insider Dev Build 22526.1000
- Headset and controllers: Oculus Rift CV1 + Touch

**Describe the bug**
After the player gets moved in a Noodle Extensions map, there is a chance that the avatar's IK feet will be way out of place, especially if there's been a large movement.

**Steps to reproduce**
1. Use full body avatar
2. Play any Noodle Extensions map with player movement (ideally large jumps)
3. Observe as the feet don't stay below you

**Expected behavior**
Feet should stay planted below you as if you weren't being moved at all.

**Screenshots**
![vlcsnap-2022-01-12-15h59m56s796](https://user-images.githubusercontent.com/20820425/149168080-ddfb7d14-dc30-4be9-8ef4-bef32d383a88.png)
![vlcsnap-2022-01-12-16h00m35s029](https://user-images.githubusercontent.com/20820425/149168088-80d74a41-5347-4fba-a069-2733390a77c4.png)
*Screenshots from [this map](https://beatsaver.com/maps/1e6ff)*

I can provide the avatar file if needed.

**Comment by nicoco007** [comment] 2022-01-19 02:49
Thanks for the report! I can confirm this is indeed an issue. I'm currently reworking a lot of tracking-related things so I'll make sure to address this while I'm at it. You can expect this to be fixed in the next release.

**Comment by nicoco007** [comment] 2023-01-19 02:17
Finally figured out what the problem was. This is now fixed in [version 5.3.0](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/tag/v5.3.0). Sorry for the wait.

**Closed by nicoco007** 2023-01-19 02:17 UTC
Labels: bug
