### ISSUE TITLE
issue with menu button on BeatSaberCustomAvatars-v5.0.0-beta.7-RELEASE

### ISSUE THREAD

**Issue by C-L-U-T-C-H** [nicoco007/BeatSaberCustomAvatars#21] opened 2020-04-09 10:33 UTC
Hi, every time i restart my PC the avatars mod menu button disappears even though my avatar is still loaded and i can see it in first and third person.  (still have full use of all the hotkeys including pgup and pgdn to switch avatar)

all my other mods show up fine. (all updated using mod assistant)

i got it working yesterday but i had to fully uninstall beatsaber and all the mods then reinstall them all just to get the avatars button back.

i am on 1.8.0 with DynamicOpenVR  (not using the .beatsaber one)
i have the steam version of the game but am using the command line argument "-vrmode oculus"

any help would be amazing! 
You can contact me on discord if you need any more info
C L U T C H#5845

**Comment by nicoco007** [comment] 2020-04-10 20:54
Could you attach your latest log? It's the file called `_latest` directly inside the `Logs` folder.

**Comment by zenmetsu** [comment] 2020-04-28 20:59
I am having this same issue.  I seldom restart my PC, but I did just recently and the mod button is gone.

I suspected that it was an issue with my new avatar that I made, so I deleted it (it was the actively used avatar) and the mod button came up... but it is happening on other avatars that were previously working.  The only difference is that I rebooted my system for the first time since installing the mod.  So to get the menu back, i have to delete the avatar that was actively set in the game so that no avatar gets loaded at startup, and the menubutton comes back.

**Comment by nicoco007** [comment] 2020-05-05 21:33
Could you attach your full latest log? It would help me figure this issue out since I haven't encountered it myself.

**Comment by zenmetsu** [comment] 2020-05-06 03:45
Attached log.  It appears to be an issue with certain avatars, but the avatars still work just fine, they simply break the mod somehow with regard to the menu button disappearing.

[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4584721/_latest.log)

**Comment by zenmetsu** [comment] 2020-05-06 03:55
BTW, I am rather responsive if you want to push test versions of the plugin to me, I'll evaluate and get back with you quickly with my findings.

**Comment by nicoco007** [comment] 2020-06-09 03:42
Turns out the root cause of this issue was the same as for #19, so this'll be fixed in the next release.

**Comment by Elementisland** [comment] 2020-06-23 07:29
In the meantime, is there a workaround for this? Getting it constantly too and I can't seem to temporarily fix it.

**Comment by nicoco007** [comment] 2020-06-30 21:46
You should be able to switch between avatars using the keyboard hotkeys (page up/page down).

To get the menu back, you either have to

1. close the game, delete/move the currently loaded avatar, start the game, and put it back
2. switch to a different avatar that doesn't trigger the error using the hotkeys and restart the game

Note that this is temporary &ndash; restarting the game with an avatar that triggers the error will continue breaking the menu.

**Comment by Elementisland** [comment] 2020-07-01 12:40
Will try this until a new version is out, thank you for the help!

**Comment by nicoco007** [comment] 2020-07-18 07:19
Beta 8 was just released and should fix this issue. If you are still having problems, feel free to reopen this issue or create a new one.

**Closed by nicoco007** 2020-07-18 07:19 UTC
