### ISSUE TITLE
Avatar steps aside and T-Poses when I select it [Version 5.2.10]

### ISSUE THREAD

**Issue by CommonStarguy** [nicoco007/BeatSaberCustomAvatars#128] opened 2022-01-19 01:02 UTC
- Windows 10
- Valve Index headset and controllers
- Game version 1.19.0 (installed using Mod Assistant version 1.1.26)

I followed [this Unity tutorial](http://stefanekren.com/deckgen/vrmtoavatar.html) to make my Vroid avatar into a Beat Saber avatar, but when I select it in-game it just steps to the side and X-poses and does nothing else but blink. I also tried downloading an older version of CustomAvatars that I found in another thread describing a similar issue, but it just got rid of the mod from my menu.

[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/7893292/_latest.log)
Attached also a video of myself selecting the avatar and the specific animation in comparison to other avatars that work correctly.
https://user-images.githubusercontent.com/83615968/150043574-930f67a1-55c6-48c0-b93f-13715fb2cf16.mp4

**Comment by nicoco007** [comment] 2022-01-19 02:54
This kind of problem is usually caused by the avatar not being set up properly. Could you either share your Unity project here or send it to me via Discord (nicoco007#2939)?

**Comment by CommonStarguy** [comment] 2022-01-19 03:08
[Here](https://drive.google.com/file/d/19OPlMcftPtia9cPckqHBdjZUpBRagWPS/view?usp=sharing) is a link to the zip file. If you notice there is something I missed I'd be so grateful to know -_-'' I'm not super versed in Unity

**Comment by nicoco007** [comment] 2022-01-19 13:20
The main problem is that you accidentally put the `AvatarDescriptor` component on the wrong GameObject. Moving it to the root GameObject should work. You can leave the other components there.

![image](https://user-images.githubusercontent.com/1349975/150136322-5660d399-8e19-4a7b-a4a0-2fc862f0d414.png)

I also have a few notes/suggestions:
1. Unless you have a specific reason to have them there, you don't need the `Cube` or `Body` GameObjects. You can delete them.
2. I am aware this is a bit confusing since the boxes are still there, but you don't need the `HeadTarget`/`LeftHandTarget`/`RightHandTarget` GameObjects anymore &ndash; as long as the `Head`/`LeftHand`/`RightHand` GameObjects are in the right spot relative to the model, the targets will be figured out automatically in-game. You can delete the target GameObjects (and make sure to remove them from `VRIKManager` as well).
3. Your `LeftHand` and `RightHand` GameObjects are backwards (i.e. left is where right should be and vice-versa).
4. You should move the `Head` GameObject forward a bit or else you might see the inside of your head in-game. 0.05 on the Z axis is usually a good starting point.

Hope this helps!

**Comment by CommonStarguy** [comment] 2022-01-19 20:09
TY so much! I wasn't aware that the steps had changed from the tutorial, but it works in game now!

**Closed** 2022-04-11 18:27 UTC
Labels: bug
