### ISSUE TITLE
Issue about the campaign ending screen.

### ISSUE THREAD

**Issue by CielTheNemesis** [nicoco007/BeatSaberCustomAvatars#56] opened 2020-08-14 20:44 UTC
[latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5077111/latest.log)

**Desktop (please complete the following information):**
- Windows 10
- Oculus Rift s

**Describe the bug**
Custom Avatar latest version (Beta8 5.0.0) Make any campaign unfinishable. The screen at the end of each level don't appear and make the level not cleared.

**Steps to reproduce**
1. Install CustomAvatar Beta8 5.0.0
2. Play a campaign level
3. See that nothing appear at the end of the level
4. See that the level is not cleared.

**Expected behavior**
The game should show the final result screen and tell you if you win or not. (everything work fine in Beta7 5.0.0)

**Comment by nicoco007** [comment] 2020-08-15 05:27
Thanks for the report! Could you try [this version](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5078231/BeatSaberCustomAvatars-3764aed-RELEASE.zip) and let me know if it works? If not, could you please attach your latest log running that version?

**Comment by nicoco007** [comment] 2020-08-17 23:47
Since I was able to reproduce and fix the issue on my end, I'm going to assume this is now fixed. Feel free to reopen this issue or create a new one if the problem persists.

**Closed by nicoco007** 2020-08-17 23:47 UTC
Labels: bug
