### ISSUE TITLE
Multiplayer Avatars

### ISSUE THREAD

**Issue by TangledWiresYT** [nicoco007/BeatSaberCustomAvatars#92] opened 2021-01-31 11:48 UTC
Can I use my normal Multiplayer avatar that everyone sees with this mod?

**Comment by nicoco007** [comment] 2021-01-31 13:43
Duplicate of #90.

TL;DR no, but you can use [NalulunaAvatars](https://youtu.be/Opbc5-x_D5k).

**Closed** 2021-01-31 13:43 UTC
Labels: duplicate, question

**Comment by TangledWiresYT** [comment] 2021-01-31 15:19
Thanks!
