### ISSUE TITLE
Crouched avatars/height issue

### ISSUE THREAD

**Issue by fuyushi** [nicoco007/BeatSaberCustomAvatars#20] opened 2020-04-03 16:35 UTC
On my old avatars (working fine at 1.7.0) the avatar always is in a crouched position on the new version. Am I supposed to remake all of them or is this a bug? To get them to strand straight I basically need to hold the HMD way above my head

Rift CV1 on steamVR
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4429238/_latest.log)

**Comment by HazardTheDutchAD** [comment] 2020-04-03 21:51
It is the same with me as well. So glad I found someone else having the same issue, now I know I am not going crazy!

**Comment by TurtleOne** [comment] 2020-04-04 12:12
Oh so that's the issue I am having. That has caused some... Questionable IK like seen here - https://streamable.com/d1angs . Again, 1.7 works. 

Note that  I cannot use the editor added to newest release as it throws compilation errors related to "Author" and "Title" from AvatarDescriptor.

**Comment by nicoco007** [comment] 2020-04-09 02:19
@fuyushi By crouching, do you mean the legs are bent or that the waist/chest is bent in a weird way? If it's the latter, since you have access to the original avatar files, could you try setting `Spine_maintain Pelvis Position` slider to 0 in IKManagerAdvanced and see if that solves the issue?

@HazardTheDutchAD You seem to be having a slightly different issue since your entire avatar seems to be sunk into the floor. Could you share your latest log when running into this issue?

@TurtleOne I've gotten a few other reports of this exact issue and they're fixed by changing `Spine_maintain Pelvis Position` when creating the avatar. Since it's not realistic to ask everyone to update just because of this, I'll be adding something that does it automatically in the next release.

**Comment by TurtleOne** [comment] 2020-04-09 18:30
I can confirm that setting Spine_maintain Pelvis Position to 0 fixes the issue. Thank you

**Comment by HugKitten** [comment] 2020-04-10 19:55
I've noticed some avatars (Neko Pink avatar) will render too low and when resized will make the player giant.


[Neko Pink.zip](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4463156/Neko.Pink.zip)

**Comment by tsuk13** [comment] 2020-04-14 19:50
@HugKitten ah yes another Neko Pink user I am having the same issue

**Comment by nicoco007** [comment] 2020-04-14 23:34
@HugKitten @tsuk13 I'm able to reproduce the issue on my end. Technically it's caused by an avatar setup issue but I believe it can be fixed without causing problems to other avatars so I'll be including a fix in the next release.

**Comment by HugKitten** [comment] 2020-04-16 23:12
Thanks dude :)

**Comment by tsuk13** [comment] 2020-04-17 16:05
Much appreciated!

**Comment by nicoco007** [comment] 2020-07-18 07:19
Beta 8 was just released and should fix this issue. If you are still having problems, feel free to reopen this issue or create a new one.

**Closed by nicoco007** 2020-07-18 07:19 UTC
Labels: bug
