### ISSUE TITLE
Incompatible with LIV (full body tracking)

### ISSUE THREAD

**Issue by CalaMariGold** [nicoco007/BeatSaberCustomAvatars#70] opened 2020-09-20 21:37 UTC
[2020.09.17.20.20.18.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5252704/2020.09.17.20.20.18.log)

**Desktop (please complete the following information):**
- Operating system: Windows 10
- Headset and controllers: Valve Index

**Describe the bug**
Custom Avatars assigns the LIV tracking camera as feet instead of the tracker I have attached to my foot
`[INFO @ 20:20:21 | CustomAvatars] [TrackedDeviceManager] Using device 'LIV Virtual Camera S/N LIV Virtual Camera (Tracker)' as LeftFoot`
Yes, I checked my controller designations in SteamVR. My trackers are assigned as Left Foot and Right Foot respectively.

**Steps to reproduce**
1. Install LIV
2. Install Custom Avatars
3. Use full body tracking
4. Try to calibrate avatar in Custom Avatars

**Expected behavior**
My foot tracker should be assigned as the foot in the avatar.

**Comment by nicoco007** [comment] 2020-09-21 20:26
Thanks for the bug report! It looks like this is actually caused by the same issue as #40 since your feet trackers aren't even being found by Unity. I'm working on a major tracking overhaul so I'll make sure to check LIV compatibility before releasing it.

**Comment by nicoco007** [comment] 2020-10-23 05:39
A fix for this will be included in the next release. If you're still having trouble once that's out, feel free to open another issue.

**Closed by nicoco007** 2020-10-23 05:39 UTC
Labels: bug
