### ISSUE TITLE
Controller z axis rotation problem in 5.2.11

### ISSUE THREAD

**Issue by Piet420** [nicoco007/BeatSaberCustomAvatars#140] opened 2022-08-31 21:32 UTC
Since version 5.2.11 the avatar hands turn in the same direction instead of the opposite direction when changing the Controller Z rotation. With my previous correct settings this causes the left hand to be rotated the wrong way. This wasn't the case in 5.2.10 and probably previous versions (Been playing on 1.16.2 until score saber got a big update...) . I tested multiple clean installs with different beat saber versions, this rotation issue happens from 1.20.0 and higher which requires the 5.2.11 version. If I load 5.2.10 in beat saber 1.24.1 then it works fine until i start a map which gives eternal black screen.
I'm happy to provide more information if needed.

**Comment by rynan4818** [comment] 2022-09-03 21:36
I am experiencing the same problem.
I am having trouble modifying LeftHandTarget for avatars distributed by modelsaber.

The cause of the problem is as follows, which was fixed in Version 5.2.11

- Fixed hands not matching controller Z rotation offset
https://github.com/nicoco007/BeatSaberCustomAvatars/commit/4664ca42e37a015cfaf4f873dc8ba13980c20f15

However, there is a reason for this fix and the current behavior may be more correct.

If you are creating your own avatar model, you may have modified LeftHandTarget with the current behavior, so it may be desirable to be able to turn it on or off in settings, etc.

At any rate, I was using a modified BeatSaberCustomAvatars with the above modification removed.

However, it seems that some other people are having trouble, so I made a patch to make it work similarly.

https://github.com/rynan4818/CustomAvatarsLeftHandPatch

**Comment by nicoco007** [comment] 2022-09-04 00:15
I don't recall exactly why that change was made but I do believe it fixed an issue someone reported to me on Discord. I did not realize it was causing problems. After digging through the latest version's code (specifically the `VRControllersValueSOOffsets` class if you're interested), it looks like Beat Games fixed the issue on their end at some point so this shouldn't be necessary anymore.

> If you are creating your own avatar model, you may have modified LeftHandTarget with the current behavior, so it may be desirable to be able to turn it on or off in settings, etc.

I was not aware people were doing this to get around the issue. It isn't really an issue if you're creating the avatar for yourself, but if it's being distributed it will prevent others from using different controller grips with it.

I will most likely remove this "fix" in the next release. If it causes issues with existing public avatars I will consider adding a toggle, but I would rather avatar creators fix it on their end if possible.

**Comment by rynan4818** [comment] 2022-09-04 00:58
I do remember that there was a problem with the previous official CONTROLLERS setting where only Rotation Z was not symmetrical.
I was using a saber that showed the direction of the pattern and wondered why it would turn in the same direction when Z was rotated.
I went back through my twitter statements and it seems that this was the case at least as far back as January 2021.

If this is a fix for this issue, I think it is fine to remove it.

For public avatars, I believe Rotation Z is assumed to be 0 degrees.

If you are making your own avatar, you may need to re-modify Target, but I don't think it is a major hassle.

**Comment by Piet420** [comment] 2022-09-04 12:58
CustomAvatarsLeftHandPatch fixed it for me, thank you very much! (i just use avatars downloaded from modelsaber)
(now i can finally play with the latest version: scoresaber down %#$% )

**Comment by nicoco007** [comment] 2023-01-19 02:19
This should now be fixed in [version 5.3.0](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/tag/v5.3.0).

**Closed by nicoco007** 2023-01-19 02:19 UTC
